add terminal widget [DRAFT]
FHPythonUtils/Cli2Gui pull request #9
Opened 2022-04-08 13:00 UTC by milahu

### What is the purpose of this pull request? (put an "X" next to item)

- [ ] Documentation update
- [ ] Bug fix
- [x] New feature
- [ ] Other

### What changes did you make? (Give an overview)

add a fully-featured bash terminal to the GUI
to show the output of the process
and to allow the user to "play" with a bash terminal

### Which issue (if any) does this pull request address?
Fixes #8

### Is there anything you'd like reviewers to focus on?

2022-04-08 16:05 UTC, FredHappyface commented
Thanks again for the work on this!

Just taken a quick look (aware that is is WIP so feel free to take these comments with a pinch of salt)

One thing that caught my eye was the inclusion of a local pysimplegui. If you've added/ changed functionality then I'd suggest raising that upstream as it may benefit other users too. And if you don't fancy that then can you monkey patch it or add the functionality in a different file (may be worth vendoring depending on the size etc)

Just a forewarning that I won't be accepting a pr with +20k lines as I don't have the time to review that

2022-04-09 19:05 UTC, milahu commented
basically working on linux, tested with [autosub](https://github.com/abhirooptalasila/AutoSub)

just needed some glue code for the file inputs
cos autosub has `type=str`
but cli2gui needs `type=argparse.FileType("rb")`

<details>
<summary>
glue code
</summary>

```py
def main():
    # run the CLI version
    parser = argparse.ArgumentParser(description="AutoSub")
    parser.add_argument(
        "--file",
        type=argparse.FileType("rb"), # -> value is io.BufferedReader(name="/path/to/file", ...)
        required=False,
        help="Input video file"
    )
    # ...
    args = parser.parse_args()
    run(args)

def run(args):
    # glue code between cli2gui and main
    # convert io.BufferedReader to str
    for file_key in ["file", "model", "scorer"]:
        file = getattr(args, file_key)
        if file:
            name = file.name
            file.close()
            setattr(args, file_key, name)
    # process args.file ...

cli2gui_decorate = Cli2Gui(
    run_function=run,
    auto_enable=True,
    program_name="AutoSub",
    program_description="Generate subtitles for videos using offline speech recognition",
)

# The gui function can be used as a GUI entrypoint
# Example: python -m mymodule:main.gui
def gui():
    if len(sys.argv) > 1: # TODO better
        main()
    else:
        gui_main = cli2gui_decorate(main)
        gui_main()
```

</details>

todo: make it work on windows, using [busybox-w32](https://github.com/rmyorston/busybox-w32)

2022-06-24 20:51 UTC, FredHappyface requested changes
Cheers for your work on this :). There's a few things that need looking at before this can be merged. Doesn't look very cross-platform which may be an issue

2022-06-24 20:51 UTC, FredHappyface commented on cli2gui/application/application.py
> +num_history_lines = 100 # aka "scrollback buffer size"
Can you try and stick by the current style guide please? Not a problem at all for a draft but this needs fixing before a merge :)

2022-06-24 20:51 UTC, FredHappyface commented on cli2gui/application/application.py
> +					buildSpec["program_description"] or
Like what you've done with the following:\


```
buildSpec["program_description"]
						if buildSpec["program_description"]
						else buildSpec["parser_description"]

```

2022-06-24 20:51 UTC, FredHappyface commented on cli2gui/application/application.py
> +	layout: list[list[Element]] = \
Can you explain the reason for changing this please? 

Also I think older versions of python crash with var: type = value even with importing annotations

2022-06-24 20:51 UTC, FredHappyface commented on cli2gui/application/application.py
> +	if False:
Guessing this is a temporary block of code?

2022-06-24 20:51 UTC, FredHappyface commented on cli2gui/application/application.py
> +	# TODO get version from pyproject.toml or from installed files
That'd be pretty awesome but happy enough with it hardcoded for now

2022-06-24 20:51 UTC, FredHappyface commented on cli2gui/application/application.py
> +			log.debug(f'child_process_watcher ---------------------------')
Looks like an f-string isn't needed here. pylint should scream about this all being well

2022-06-24 20:51 UTC, FredHappyface commented on pyproject.toml
> +Pillow = ">=9"
Please try and use project tooling to manage this, setting Pillow = ">=9" breaks semver (even if not a perfect system)

2022-06-24 20:51 UTC, FredHappyface commented on pyproject.toml
> +pyte = ">= 0.8.0"
Should probably have these be optional if unix only packages

2022-06-24 20:51 UTC, FredHappyface commented on pyproject.toml
> +#PySimpleGUI: bundled locally. need unreleased git version for propagate=False
This needs to not be bundled locally before merging

2022-06-24 21:48 UTC, milahu commented
sorry for abandoning this

iirc, the big issues were

* to render ansi color escapes, we need to rewrite pyte-screen for tkinter.Text (bypass psg for better perf)
  * line wrapping in tkinter.Text is extremely slow, so we must do our own line wrapping (in pyte)
  * allow resizing the terminal = re-calculate all line-wraps
* bash job control (ctrl-z, jobs, bg, fg) was not working on windows (preexec_fn=os.setsid) (setsid is unix only)

for performance, its probably better to render the terminal with [alacritty](https://github.com/alacritty/alacritty/issues/450) or [kitty](https://github.com/kovidgoyal/kitty)
embedded into some widgets for menus and input forms

related

* https://github.com/lxqt/qtermwidget
* https://github.com/prompt-toolkit/ptterm
* https://github.com/spyder-ide/pywinpty
* https://github.com/Saadmairaj/tkterminal

im still surprised that qt/gtk/tk dont have cross-platform ansi terminal widgets ...

2022-06-27 18:54 UTC, FredHappyface commented
Dw about it 

Yeah agreed that there don't appear to be tons of solutions. Though what confuses me about this all is why you wouldn't use use your fav terminal to start the process in the first place?

If you're done with this then I'll probably close the pr

As you probably know you are absolutely welcome to fork this if you want/ need this feature. Just for it to be part of this project it could really do with being platform independent

Thank you for all your time on this though. Definitely appreciated! - it's nice to see that the project is useful to others too

2022-06-27 19:07 UTC, milahu commented
> why you wouldn't use use your fav terminal to start the process in the first place?

im thinking of "the user" who starts a gui app, enters his data via gui
and expects the process to run as if it was started from a terminal emulator
(but gui and terminal should be the same window)
as bonus, the user gets features like bash job control, or command history

anyway, closing as abandoned : /

2022-06-27 19:07 UTC, closed without merging